### ISSUE TITLE
[Meta] - Calculator

### ISSUE THREAD

**Issue by wesruv** [wesruv/scorinator#1]
Feel free to make tickets for these if you grab a task
- [ ] Style Calculator
- [ ] Calculator Storage/Data layer
- [ ] Basic calculation functionality
- [ ] Enter, new line, add a step of 'history' behavior
- [ ] Undo behavior

![image](https://cloud.githubusercontent.com/assets/5607236/13040578/fcc23174-d37b-11e5-8297-90e424bc8c52.png)
