### ISSUE TITLE
[META] Add Players functionality

### ISSUE THREAD

**Issue by wesruv** [wesruv/scorinator#8]
Cut tickets as you grab one of these tickets and link the ticket in this description.
- [ ] Define Players data structure
- [ ] Add `data-handlers`
- [ ] Recent Players functionality
- [ ] Add "Manual"/"Quick Add" player functionality
- [ ] Add from Contacts functionality

![image](https://cloud.githubusercontent.com/assets/5607236/13040605/6156a8d6-d37c-11e5-8e06-8e4f496948cc.png)
